In [1]:
import numpy as np

In [2]:
one_dimensional_arr = np.array([10, 12])
one_dimensional_arr

array([10, 12])

In [3]:
b = np.arange(3)
b

array([0, 1, 2])

shift + tab - allows to access the documentation of any function

In [4]:
c = np.arange(1, 20, 3, dtype=float)
c

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [5]:
d = np.linspace(0, 100, 5, dtype=int)
d

array([  0,  25,  50,  75, 100])

In [6]:
char_arr = np.array(['Numpy is awesome'])
char_arr

array(['Numpy is awesome'], dtype='<U16')

In [7]:
ones_arr = np.ones(3, dtype=int)
ones_arr

array([1, 1, 1])

In [8]:
zeros_arr = np.zeros(3, dtype=int)
zeros_arr

array([0, 0, 0])

In [9]:
empty_arr = np.empty(3, dtype=int)
empty_arr

array([4456521, 5111877, 4784212])

In [10]:
rand_arr = np.random.rand(3)
rand_arr

array([0.68832217, 0.75788813, 0.15718337])

Multidimensional arrays

In [11]:
two_dim_arr = np.array([[1, 2, 3], [6, 5, 4]])
two_dim_arr

array([[1, 2, 3],
       [6, 5, 4]])

In [12]:
one_dim_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(one_dim_arr)

multi_dim_arr = np.reshape(one_dim_arr, (3, 1, 3))

print(multi_dim_arr)

[1 2 3 4 5 6 7 8 9]
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


Finding size, shape and dimension

In [13]:
multi_dim_arr.ndim

3

In [14]:
multi_dim_arr.shape

(3, 1, 3)

In [15]:
multi_dim_arr.size

9

Array math operations

In [16]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 5, 5])

addition = arr_1 + arr_2
print(addition)

subtraction = arr_1 - arr_2
print(subtraction)

multiplication = arr_1 * arr_2
print(multiplication)

division = arr_1 / arr_2
print(division)

division = arr_1 % arr_2
print(division)

division = arr_1 // arr_2
print(division)

[ 3  9 11]
[ 1 -1  1]
[ 2 20 30]
[2.  0.8 1.2]
[0 4 1]
[2 0 1]


Operations with scalar

In [17]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(vector * 1.6, vector + 1.6, 
      vector - 1.6, vector / 1.6,
      vector // 2, vector % 2)

[ 1.6  3.2  4.8  6.4  8.   9.6 11.2 12.8 14.4 16.  17.6] [ 2.6  3.6  4.6  5.6  6.6  7.6  8.6  9.6 10.6 11.6 12.6] [-0.6  0.4  1.4  2.4  3.4  4.4  5.4  6.4  7.4  8.4  9.4] [0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.    5.625 6.25  6.875] [0 1 1 2 2 3 3 4 4 5 5] [1 0 1 0 1 0 1 0 1 0 1]


Indexing and slicing

In [18]:
print(vector[0], vector[4:8])

1 [5 6 7 8]


In [19]:
two_dim = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [20]:
two_dim[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

Stacking

In [21]:
a1 = np.array([[1,1],
               [2,3]])

a2 = np.array([[4,5],
               [6,7]])

vert_stack = np.vstack([a1, a2])
vert_stack

array([[1, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
horiz_stack = np.hstack([a1, a2])
horiz_stack

array([[1, 1, 4, 5],
       [2, 3, 6, 7]])

Numpy 100 exercises